### ISSUE TITLE
Support definition lists w/o blank lines

### ISSUE THREAD

**Issue by mdekstrand** [Symbitic/remark-plugins#7]
Thanks for these extensions! I've been looking for a definition list extension for a while.

Right now, though, the definition list requires a blank line between term and definition:

```markdown
term

:  definition
```

Other implementations of comparable syntax — Pandoc and PyMarkdown's definition list extension — do not require the blank line:

```markdown
term
:    definition
```

Any chance the `remark-deflist` extensino could support this more flexible syntax as well?

**Comment by Symbitic** [comment]
Fixed in 9d4442568d4f16b03c2435335fc3eea0b46be2fc.
